services:
  mysql07:
    image: mysql
    container_name: mysql07
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - pregrancy-trackers

#  redis08:
#    image: redis/redis-stack:latest
#    container_name: redis08
#    ports:
#      - "6379:6379"
#      - "8001:8001"
#    networks:
#      -uni-club

networks:
  uni-club:
    driver: bridge