services:
  mysql07:
    image: mysql
    container_name: mysql07
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - product-sale

  redis08:
    image: redis/redis-stack:latest
    container_name: redis08
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-data:/data
    networks:
      - product-sale

networks:
  product-sale:
    driver: bridge